# Generated by Django 2.2.5 on 2024-07-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
