# Generated by Django 2.2.5 on 2024-07-09 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240704_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='detalhe_url',
        ),
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='curso',
            name='criados',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='compra_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Link compra'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='URL IMG'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='#', max_digits=10, verbose_name='Preço'),
        ),
    ]
